### ISSUE TITLE
convert onyx nutritionLabel to full_nutrients array

### ISSUE THREAD

**Issue by vgupta16** [nutritionix/nutritionix-api-data-utilities#8]
example onyx nutritionLabel: https://gist.github.com/vgupta16/7105fb3dc9db37ccce9b6618b609d124

subset of id mappings:
{
  "127271": 204,
  "127272": 606,
  "132289": 605,
  "127275": 601,
  "127276": 307,
  "127278": 205,
  "127279": 291,
  "127282": 269,
  "127285": 203,
  "127277": 306,
  "Calorie.Calories": 208,
  "127273": 646,
  "127274": 645
}

I hope to have a full mapping for you soon, but at least we can get started with this. I can also send you more sample onyx nutritionLabel objects for testing purposes.

For the first iteration:
 - we will go from onyx json -> full_nutrients array
 - Only map nutrient values and disregard vitamins and minerals

Later iteration:
 - we will want to go from full_nutrients array to onyx json
 - map all nutrients as well as vitamins and minerals (this might require custom logic if we need to do percent daily value transforms)

**Comment by Yurko-Fedoriv** [comment]
@vgupta16 I have published https://github.com/nutritionix/nutritionix-api-data-utilities/tree/2.3.1
with `convertOnyxToFullNutrientsArray` method.
Please let me know how it works for you.

**Comment by Yurko-Fedoriv** [comment]
note, I used `Facts[x].Uom.Value` as values.
But those values are a bit strange in the example file. Is this because the file is just a demo, or am I doing something wrong?

**Comment by vgupta16** [comment]
@Yurko-Fedoriv I believe the values should be taken from `Facts[x].Quantity`

The structure is a little strange. I believe the `Uom.Value` is referring to the id of that particular Uom.

**Comment by Yurko-Fedoriv** [comment]
@vgupta16 oh, I see.
I've deployed https://github.com/nutritionix/nutritionix-api-data-utilities/tree/2.3.2 to address this

**Comment by vgupta16** [comment]
Thanks. Will test it out today
